@startuml
hide empty members
hide circle
top to bottom direction

:Subscriber:
(Create connection) as (C)
note top of (C): Necessary for subscribing
Subscriber --> C

:Publisher:
(Publish)
Publisher --> Publish

@enduml
