{
  parserClass="com.intellij.sdk.language.parser.SimpleParser"

  extends="com.intellij.extapi.psi.ASTWrapperPsiElement"

  psiClassPrefix="Simple"
  psiImplClassSuffix="Impl"
  psiPackage="com.intellij.sdk.language.psi"
  psiImplPackage="com.intellij.sdk.language.psi.impl"

  elementTypeHolderClass="com.intellij.sdk.language.psi.SimpleTypes"
  elementTypeClass="com.intellij.sdk.language.psi.SimpleElementType"
  tokenTypeClass="com.intellij.sdk.language.psi.SimpleTokenType"

  psiImplUtilClass="com.intellij.sdk.language.psi.impl.SimplePsiImplUtil"
}

simpleFile ::= item_*

private item_ ::= (property|COMMENT|CRLF)

property ::= (KEY? SEPARATOR VALUE?) | KEY {
  pin=3
  recoverWhile="recover_property"
  mixin="com.intellij.sdk.language.psi.impl.SimpleNamedElementImpl"
  implements="com.intellij.sdk.language.psi.SimpleNamedElement"
  methods=[getKey getValue getName setName getNameIdentifier getPresentation]
}

private recover_property ::= !(KEY|SEPARATOR|COMMENT)