#!/usr/bin/env kotlin

// Copyright 2000-2025 JetBrains s.r.o. and contributors. Use of this source code is governed by the Apache 2.0 license.

/**
 * This script is used to update the versions of libraries stored in the v.list releases file.
 */
@file:DependsOn("org.jetbrains.kotlinx:kotlinx-serialization-json-jvm:1.7.0-RC")

import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonArray
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.File
import java.net.URL

val FILE_PATH = "v.list"

val releasesList = mapOf(
  "intellij-platform-gradle-plugin-version" to ReleaseInfo(
    type = ReleaseInfo.Type.GitHub,
    url = "https://api.github.com/repos/JetBrains/intellij-platform-gradle-plugin/releases",
    transformer = { list -> list.first { it.startsWith("2.") } }
  ),
  "gradle-intellij-plugin-version" to ReleaseInfo(
    type = ReleaseInfo.Type.GitHub,
    url = "https://api.github.com/repos/JetBrains/intellij-platform-gradle-plugin/releases",
    transformer = { list -> list.first { it.startsWith("1.") } }
  ),
  "gradle-grammar-kit-plugin-version" to ReleaseInfo(
    type = ReleaseInfo.Type.GitHub,
    url = "https://api.github.com/repos/JetBrains/gradle-grammar-kit-plugin/releases"
  ),
  "plugin-verifier-version" to ReleaseInfo(
    type = ReleaseInfo.Type.GitHub,
    url = "https://api.github.com/repos/JetBrains/intellij-plugin-verifier/releases"
  ),
  "marketplace-zip-signer-version" to ReleaseInfo(
    type = ReleaseInfo.Type.GitHub,
    url = "https://api.github.com/repos/JetBrains/marketplace-zip-signer/releases"
  )
)

val vars = releasesList.mapValues { (key, releaseInfo) ->
  when (releaseInfo.type) {
    ReleaseInfo.Type.GitHub -> run {
      try {
        val content = URL(releaseInfo.url).readText()
        Json.decodeFromString<JsonArray>(content)
          .mapNotNull { it.jsonObject["name"] }
          .map { it.jsonPrimitive.content.removePrefix("v").removePrefix("Version ") }
          .run(releaseInfo.transformer)
      } catch (e: Exception) {
        println("Cannot resolve the latest '$key' version: ${e.message}")
        throw e
      }
    }
  }
}.map { (key, version) ->
  "<var name=\"$key\" value=\"$version\"/>"
}

val newFileContent = StringBuilder()
val patternToInsertAfter = "<!-- GENERATED CONTENT START -->"
val patternToSkipUntil = "<!-- GENERATED CONTENT END -->"

file(FILE_PATH).useLines { lines ->
  var insideGeneratedContent = false
  for (line in lines) {
    if (line.trim() == patternToInsertAfter) {
      insideGeneratedContent = true
      newFileContent.appendLine(line)
      newFileContent.appendLine("  <!-- This content is generated by libraries_releases.main.kts script. -->")
      newFileContent.appendLine("  <!-- DO NOT EDIT IT MANUALLY -->")
      newFileContent.appendLine(vars.joinToString(prefix = "  ", separator = "\n  "))
    } else if (line.trim() == patternToSkipUntil) {
      insideGeneratedContent = false
      newFileContent.appendLine(line)
    } else if (!insideGeneratedContent) {
      newFileContent.appendLine(line)
    }
  }
}

file(FILE_PATH).writeText(newFileContent.toString())

fun file(path: String) = File(System.getenv("GITHUB_WORKSPACE") ?: "../../").resolve(path).also(File::createNewFile)

data class ReleaseInfo(
  val type: Type,
  val url: String,
  val transformer: (List<String>) -> String = { it.first() },
) {

  enum class Type { GitHub }
}
