elements:
  - name: idea-plugin
    requirement:
      required: yes
    #language=Markdown
    description: The <path>plugin.xml</path> file root element.

    attributes:
      - name: url
        required: no
        #language=Markdown
        requiredDetails: &ignoredInAdditionalPluginXml |
          ignored in an [additional config file](https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html#additional-plugin-configuration-files)
        #language=Markdown
        description: The link to the plugin homepage displayed on the plugin page in the [JetBrains Marketplace](https://plugins.jetbrains.com).
      - name: require-restart
        required: no
        defaultValue: false
        #language=Markdown
        description: |
          The boolean value determining whether the plugin installation, update, or uninstallation requires the IDE restart (see [](dynamic_plugins.md) for details).

    children:
      - name: id
        #language=Markdown
        description: |
          A unique identifier of the plugin.
          It should be a fully qualified name similar to Java packages and must not collide with the ID of existing plugins.
          The ID is a technical value used to identify the plugin in the IDE and [JetBrains Marketplace](https://plugins.jetbrains.com).
          Please use characters, numbers, and `'.'`/`'-'`/`'_'` symbols only and keep it reasonably short.

          > Make sure to pick a stable ID, as the value cannot be changed later after public release.
          >
          {style="warning"}
        requirement:
          required: no
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - |
                **It is highly recommended to set in <path>plugin.xml</path> file.**
            - &patchXmlGradleTask |
                The element can be skipped in the source <path>plugin.xml</path> file if the Gradle plugin `patchPluginXml` task
                ([2.x](https://plugins.jetbrains.com/docs/intellij/tools-intellij-platform-gradle-plugin-tasks.html#patchPluginXml),
                [1.x](https://plugins.jetbrains.com/docs/intellij/tools-gradle-intellij-plugin.html#tasks-patchpluginxml))
                is enabled and configured.
        #language=Markdown
        defaultValue: Value of the [`<name>`](#idea-plugin__name) element.
        #language=Markdown
        examples:
          - |
              ```xml
              <id>com.company.framework</id>
              ```

      - name: name
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: Plugin Name](https://plugins.jetbrains.com/docs/marketplace/plugin-overview-page.html#plugin-name)
        #language=Markdown
        description: The user-visible plugin display name (Title Case).
        requirement:
          required: yes
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
        examples:
          #language=Markdown
          - |
              ```xml
              <name>My Framework Support</name>
              ```

      - name: version
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: Semantic Versioning](https://plugins.jetbrains.com/docs/marketplace/semver.html)
        #language=Markdown
        description: |
          The plugin version displayed in the <control>Plugins</control> settings dialog and in the JetBrains Marketplace plugin page.
          Plugins uploaded to the JetBrains Marketplace must follow semantic versioning.
        requirement:
          required: yes
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - *patchXmlGradleTask
        #language=Markdown
        examples:
          - |
              ```xml
              <version>1.3.18</version>
              ```

      - name: product-descriptor
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: How to add required parameters for paid plugins](https://plugins.jetbrains.com/docs/marketplace/add-required-parameters.html)
        #language=Markdown
        description: |
          [Paid](https://plugins.jetbrains.com/build-and-market) or [Freemium](https://plugins.jetbrains.com/docs/marketplace/freemium.html) plugin descriptor.
        requirement:
          required: yes_for_paid
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - |
                **Do not add `<product-descriptor>` element in a free plugin.**
        attributes:
          - name: code
            required: yes
            #language=Markdown
            description: |
              The plugin product code used in the JetBrains Sales System.
              The code must be agreed with JetBrains in advance and follow [the requirements](https://plugins.jetbrains.com/docs/marketplace/obtain-a-product-code-from-jetbrains.html).
          - name: release-date
            required: yes
            #language=Markdown
            description: Date of the major version release in the `YYYYMMDD` format.
          - name: release-version
            required: yes
            #language=Markdown
            description: A major version in a special number format.
          - name: optional
            required: no
            #language=Markdown
            description: The boolean value determining whether the plugin is a [Freemium](https://plugins.jetbrains.com/docs/marketplace/freemium.html) plugin.
            defaultValue: false
          - name: eap
            required: no
            #language=Markdown
            description: Specifies the boolean value determining whether the plugin is an EAP release.
            defaultValue: false
        #language=Markdown
#        examples:
#          - |
#              ```xml
#              TODO?
#              ```

      - name: idea-version
        #language=Markdown
        references:
          - |
              [Build Number Ranges](https://plugins.jetbrains.com/docs/intellij/build-number-ranges.html)
        #language=Markdown
        description: The plugin's range of compatible IntelliJ-based IDE versions.
        requirement:
          required: yes
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - *patchXmlGradleTask
        attributes:
          - name: since-build
            required: yes
            #language=Markdown
            description: The lowest IDE version compatible with the plugin.
          - name: until-build
            required: no
            #language=Markdown
            description: |
              The highest IDE version compatible with the plugin.
              Undefined value declares compatibility with all the IDEs since the version specified by the `since-build`
              (also with the future builds what may cause incompatibility errors).
        #language=Markdown
        examples:
          - | # code snippets must have 4 spaces indent here
              Compatibility with a specific build number (2021.3.3) and higher versions:
                  ```xml
                  <idea-version since-build="213.7172.25"/>
                  ```
          - |
              Compatibility with versions from any of `213` branches to any of `221` branches:
                  ```xml
                  <idea-version
                      since-build="213" until-build="221.*"/>
                  ```

      - name: vendor
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: Contacts and Resources](https://plugins.jetbrains.com/docs/marketplace/plugin-overview-page.html#contacts-and-resources)
        #language=Markdown
        description: The vendor name or organization ID (if created) in the <control>Plugins</control> settings dialog and in the JetBrains Marketplace plugin page.
        requirement:
          required: yes
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
        attributes:
          - name: url
            required: no
            #language=Markdown
            description: |
              The URL to the vendor's homepage.
              Supports `https://` and `http://` scheme links.
          - name: email
            required: no
            #language=Markdown
            description: The vendor's email address.
        #language=Markdown
        examples:
          - | # code snippets must have 4 spaces indent here
              Personal vendor with an email address provided:
                  ```xml
                  <vendor email="joe@example.com">Joe Doe</vendor>
                  ```
          - |
              Organizational vendor with a website URL and email address provided:
                  ```xml
                  <vendor
                      url="https://mycompany.example.com"
                      email="contact@example.com">
                    My Company
                  </vendor>
                  ```

      - name: description
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: Plugin Description](https://plugins.jetbrains.com/docs/marketplace/plugin-overview-page.html#plugin-description)
        #language=Markdown
        description: |
          The plugin description displayed on the JetBrains Marketplace plugin page and in the <control>Plugins</control> settings dialog.

          Simple HTML elements, like text formatting, paragraphs, lists, etc., are allowed and must be wrapped into `<![CDATA[` ... `]]>` section.
        requirement:
          required: yes
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - *patchXmlGradleTask
        #language=Markdown
        examples:
          - |
            ```xml
            <description><![CDATA[
            Provides support for My Framework.
            The support includes:
            <ul>
              <li>code completion</li>
              <li>references</li>
            </ul>
            For more information visit the
            <a href="https://example.com">project site</a>.
            ]]></description>
            ```

      - name: change-notes
        #language=Markdown
        references:
          - |
              [JetBrains Marketplace: Change Notes](https://plugins.jetbrains.com/docs/marketplace/plugin-overview-page.html#change-notes)
        #language=Markdown
        description: |
          A short summary of new features, bugfixes, and changes provided with the latest plugin version.
          Change notes are displayed on the JetBrains Marketplace plugin page and in the <control>Plugins</control> settings dialog.

          Simple HTML elements, like text formatting, paragraphs, lists, etc., are allowed and must be wrapped into `<![CDATA[` ... `]]>` section.
        requirement:
          required: no
          #language=Markdown
          details:
            - *ignoredInAdditionalPluginXml
            - *patchXmlGradleTask
        #language=Markdown
        examples:
          - |
              ```xml
              <change-notes><![CDATA[
              <h2>New Features</h2>
              <ul>
                <li>Feature 1</li>
                <li>Feature 2</li>
              </ul>
              <h2>Bug Fixes</h2>
              <ul>
                <li>Fixed issue 1</li>
                <li>Fixed issue 2</li>
              </ul>
              ]]></change-notes>
              ```

      - name: depends
        #language=Markdown
        references:
          - |
              [Plugin Dependencies](https://plugins.jetbrains.com/docs/intellij/plugin-dependencies.html)
          - |
              [Modules Specific to Functionality](https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#modules-specific-to-functionality)
        #language=Markdown
        description: |
          Specifies a dependency on another plugin or a module of an IntelliJ Platform-based product.
          A single [`<idea-plugin>`](#idea-plugin) element can contain multiple `<depends>` elements.

        requirement:
          required: no
          #language=Markdown
          details:
            - in most cases dependency on the [platform](https://plugins.jetbrains.com/docs/intellij/plugin-compatibility.html#modules-available-in-all-products) module is needed
        attributes:
          - name: optional
            required: no
            #language=Markdown
            description: |
              Boolean value defining whether the dependency is optional to load the plugin in the IDE.
              If the dependency plugin is not installed in the current IDE, and `optional` is:
                - `true` - the plugin will be loaded
                - `false` (default) - the plugin will not be loaded
          - name: config-file
            required: no
            #language=Markdown
            description: |
              Relative path to an [additional configuration file](https://plugins.jetbrains.com/docs/intellij/plugin-configuration-file.html#additional-plugin-configuration-files), loaded only if the dependency plugin is installed in the current IDE.
        #language=Markdown
        examples:
        - |
            Required plugin dependency:
                ```xml
                <depends>com.example.dependencypluginid</depends>
                ```
        - |
            Required dependency on the IntelliJ IDEA Java Module:
                ```xml
                <depends>com.intellij.modules.java</depends>
                ```
        - |
            Optional plugin dependency:
                ```xml
                <depends optional="true">
                  com.example.dependencypluginid
                </depends>
                ```
        - |
            Required module dependency with additional configuration:
                ```xml
                <depends
                    config-file="myPluginId-withJava.xml">
                  com.intellij.modules.java
                </depends>
                ```
        - |
            Optional module dependency with additional configuration:
                ```xml
                <depends
                    optional="true"
                    config-file="myPluginId-withKotlin.xml">
                  org.jetbrains.kotlin
                </depends>
                ```
