name: Generate Libraries releases variable file

on:
  schedule:
    - cron: "1 1 * * *"
  workflow_dispatch:

jobs:
  generate:
    if: github.ref == 'refs/heads/main' && github.repository == 'JetBrains/intellij-sdk-docs'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - name: Generate
        run: "${GITHUB_WORKSPACE}/.github/scripts/libraries_releases.main.kts"
      - name: Commit changes
        uses: Endbug/add-and-commit@v11
        with:
          message: 'Generate Libraries releases variable file'
          add: 'v.list'
